version: "3.9"

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: bookkeeper_db
    volumes:
      - db_data:/data/db
    ports:
      - "5005:27017"
volumes:
  db_data:
